ExUnit.configure(formatters: [JUnitFormatter, ExUnit.CLIFormatter])
ExUnit.start(capture_log: true, exclude: [:skip])
Ecto.Adapters.SQL.Sandbox.mode(Devhub.Repo, :manual)

Mimic.copy(Devhub, type_check: true)
Mimic.copy(Devhub.ApiKeys, type_check: true)
Mimic.copy(Devhub.Calendar, type_check: true)
Mimic.copy(Devhub.Calendar.Storage, type_check: true)
Mimic.copy(Devhub.Coverbot, type_check: true)
Mimic.copy(Devhub.Integrations, type_check: true)
Mimic.copy(Devhub.Integrations.AI, type_check: true)
Mimic.copy(Devhub.Integrations.GitHub, type_check: true)
Mimic.copy(Devhub.Integrations.GitHub.AppToken, type_check: true)
Mimic.copy(Devhub.Integrations.GitHub.Client, type_check: true)
Mimic.copy(Devhub.Integrations.GitHub.Storage, type_check: true)
Mimic.copy(Devhub.Integrations.Google, type_check: true)
Mimic.copy(Devhub.Integrations.Kubernetes.Client, type_check: true)
Mimic.copy(Devhub.Integrations.Linear, type_check: true)
Mimic.copy(Devhub.Integrations.Slack, type_check: true)
Mimic.copy(Devhub.Licensing.Client, type_check: true)
Mimic.copy(Devhub.QueryDesk, type_check: true)
Mimic.copy(Devhub.QueryDesk.Databases.Adapter, type_check: true)
Mimic.copy(Devhub.Repo, type_check: true)
Mimic.copy(Devhub.Shared, type_check: true)
Mimic.copy(Devhub.TerraDesk, type_check: true)
Mimic.copy(Devhub.TerraDesk.TerraformStateCache, type_check: true)
Mimic.copy(Devhub.Uptime, type_check: true)
Mimic.copy(Devhub.Uptime.RequestTracerService, type_check: true)
Mimic.copy(Devhub.Users, type_check: true)
Mimic.copy(Devhub.Utils.RunShellCommand, type_check: true)
Mimic.copy(Devhub.Workflows, type_check: true)
Mimic.copy(DevhubProtos.RequestTracer.V1.RequestTracerService.Stub, type_check: true)
Mimic.copy(DevhubWeb.AgentConnection, type_check: true)
Mimic.copy(OpenIDConnect, type_check: true)
Mimic.copy(Tesla.Adapter.Finch, type_check: true)
Mimic.copy(Wax, type_check: true)
