name: Generate Test Reports

on:
  workflow_dispatch:
  schedule:
    # at minute 13 hourly.
    # Not picking the beginning of the hour, because that's why the runners are busiest
    - cron: 13 * * * *

permissions:
  checks: write
  contents: read
  pull-requests: read
  statuses: write

env:
  MIX_ENV: test

jobs:
  test:
    name: Tests
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@1117842ea70e2711a0072e3a71265cbfe2c830be

      - name: Cache Deps
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: mix do deps.get, compile --warnings-as-errors, ecto.drop --quiet, ecto.create, ecto.migrate

      - name: Run Tests
        continue-on-error: true
        run: mix coveralls.json --max-cases 4

      - name: Check Code Coverage
        if: always()
        uses: devhub-tools/coverbot-action@v1
        with:
          domain: private.devhub.cloud
          format: elixir
          file: cover/excoveralls.json
          devhub_api_key: ${{ secrets.DEVHUB_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          junit_folder: junit
