name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: read
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true


env:
  MIX_ENV: test

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Mise
        uses: jdx/mise-action@v2

      - name: Docker Compose
        run: docker compose up -d

      - name: Cache Deps
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: mix do deps.get, compile --warnings-as-errors, ecto.drop --quiet, ecto.create, ecto.migrate
      - run: mix coveralls.json --max-cases 4

      - name: Check Code Coverage
        if: always()
        uses: devhub-tools/coverbot-action@v1
        with:
          domain: private.devhub.cloud
          format: elixir
          file: cover/excoveralls.json
          devhub_api_key: ${{ secrets.DEVHUB_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: .tool-versions

      - name: Cache Deps
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: mix do deps.get, compile
      - run: mix format --check-formatted

  credo:
    name: Credo
    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: .tool-versions

      - name: Cache Deps
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-dev-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-dev-

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-dev-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-dev-

      - run: mix do deps.get, compile
      - run: mix credo
